#!/bin/bash -e
 
PROJECT="$(basename `pwd`)"
DEPLOY_ENV="${DEPLOY_ENV:-test}"
 
init() {
  if [ -d .terraform ]; then
    if [ -e .terraform/terraform.tfstate ]; then
      echo "Remote state already exist!"
      if [ -z $IGNORE_INIT ]; then
        exit 1
      fi
    fi
  fi
 
 
  terraform remote config \
    -backend=consul \
    -backend-config="path=$PROJECT/$DEPLOY_ENV"
 
}
 
while getopts "i" opt; do
  case "$opt" in
    i)
      IGNORE_INIT="true"
      ;;
  esac
done
 
shift $((OPTIND-1))
 
init